### PR TITLE
Add a quicli script to trace malloc and frees and turn them into test inputs!

### PR DESCRIPTION
**Pull request by fitzgen**
This introduces a script that uses `valgrind` to trace some program's mallocs and frees, and then it turns those into something that can be used as test/benchmark inputs for `wee_alloc`.

cc @alexcrichton; you may also find this useful for the other rust allocators you maintain ;)

### CODE REVIEW

**Comment by alexcrichton** [comment]
🙉

**Comment by fitzgen** [comment]
For some reason, this makes release builds time out... Presumably from the `include!`ing of the big trace file?

**Comment by fitzgen** [comment]
I guess I can parse the trace at runtime rather than use `include!`.

**Comment by fitzgen** [comment]
Tests are passing now \o/

**Comment by fitzgen** [comment]
Impact of enabling size classes on the performance of these traces:

```

 name                          bench.txt ns/iter  bench-size-classes.txt ns/iter  diff ns/iter   diff %  speedup 
 bench_trace_cpp_demangle      16,815,378         187,824                          -16,627,554  -98.88%  x 89.53 
 bench_trace_dogfood           2,157,410          10,325,746                         8,168,336  378.62%   x 0.21 
 bench_trace_ffmpeg            95,496,531         998,136                          -94,498,395  -98.95%  x 95.67 
 bench_trace_find              1,014,857          38,984                              -975,873  -96.16%  x 26.03 
 bench_trace_gcc_hello         21,291,728         1,761,312                        -19,530,416  -91.73%  x 12.09 
 bench_trace_grep_random_data  17,389,509         2,418,104                        -14,971,405  -86.09%   x 7.19 
 bench_trace_grep_recursive    1,591,923          1,220,415                           -371,508  -23.34%   x 1.30 
 bench_trace_ls                2,067,298          576,167                           -1,491,131  -72.13%   x 3.59 
bench_trace_source_map 1,739,317 184,998 -1,554,319 -89.36% x 9.40 
```

**Comment by pepyakin** [comment]
And sorry for the delay!

**Pull request merged**
